In [41]:
from sklearn.datasets import load_diabetes
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge,Lasso
from sklearn.metrics import mean_squared_error,r2_score

In [2]:
data=load_diabetes()

In [11]:
X=pd.DataFrame(data.data,columns=data.feature_names)

In [12]:
X.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641

In [17]:
y=data.target

In [18]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 288.,  88., 292.,  71.,
       197., 186.,  25.,  84.,  96., 195.,  53., 217., 172., 131., 214.,
        59.,  70., 220., 268., 152.,  47.,  74., 295., 101., 151., 127.,
       237., 225.,  81., 151., 107.,  64., 138., 185., 265., 101., 137.,
       143., 141.,  79., 292., 178.,  91., 116.,  86., 122.,  72., 129.,
       142.,  90., 158.,  39., 196., 222., 277.,  99., 196., 202., 155.,
        77., 191.,  70.,  73.,  49.,  65., 263., 248., 296., 214., 185.,
        78.,  93., 252., 150.,  77., 208.,  77., 108., 160.,  53., 220.,
       154., 259.,  90., 246., 124.,  67.,  72., 257., 262., 275., 177.,
        71.,  47., 187., 125.,  78.,  51., 258., 215., 303., 243.,  91.,
       150., 310., 153., 346.,  63.,  89.,  50.,  39., 103., 308., 116.,
       145.,  74.,  45., 115., 264.,  87., 202., 127., 182., 241.,  66.,
        94., 283.,  64., 102., 200., 265.,  94., 230., 181., 156., 233.,
        60., 219.,  80.,  68., 332., 248.,  84., 200.,  55.,  85.,  89.,
        31., 129.,  83., 275.,  65., 198., 236., 253., 124.,  44., 172.,
       114., 142., 109., 180., 144., 163., 147.,  97., 220., 190., 109.,
       191., 122., 230., 242., 248., 249., 192., 131., 237.,  78., 135.,
       244., 199., 270., 164.,  72.,  96., 306.,  91., 214.,  95., 216.,
       263., 178., 113., 200., 139., 139.,  88., 148.,  88., 243.,  71.,
        77., 109., 272.,  60.,  54., 221.,  90., 311., 281., 182., 321.,
        58., 262., 206., 233., 242., 123., 167.,  63., 197.,  71., 168.,
       140., 217., 121., 235., 245.,  40.,  52., 104., 132.,  88.,  69.,
       219.,  72., 201., 110.,  51., 277.,  63., 118.,  69., 273., 258.,
        43., 198., 242., 232., 175.,  93., 168., 275., 293., 281.,  72.,
       140., 189., 181., 209., 136., 261., 113., 131., 174., 257.,  55.,
        84.,  42., 146., 212., 233.,  91., 111., 152., 120.,  67., 310.,
        94., 183.,  66., 173.,  72.,  49.,  64.,  48., 178., 104., 132.,
       220.,  57.])

In [20]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [22]:
X_train.shape

(353, 10)

In [23]:
y_train.shape

(353,)

In [25]:
X_train.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
17,0.070769,0.050680,0.012117,0.056301,0.034206,0.049416,-0.039719,0.034309,0.027364,-0.001078
66,-0.009147,0.050680,-0.018062,-0.033213,-0.020832,0.012152,-0.072854,0.071210,0.000272,0.019633
137,0.005383,-0.044642,0.049840,0.097615,-0.015328,-0.016345,-0.006584,-0.002592,0.017036,-0.013504
245,-0.027310,-0.044642,-0.035307,-0.029770,-0.056607,-0.058620,0.030232,-0.039493,-0.049872,-0.129483
31,-0.023677,-0.044642,-0.065486,-0.081413,-0.038720,-0.053610,0.059685,-0.076395,-0.037129,-0.042499

In [26]:
print(y_train)

[144. 150. 280. 125.  59.  65. 281. 277. 167.  90.  72. 178.  88. 270.
 101. 197.  97.  53.  71. 262.  52. 102. 166. 189. 173. 220. 206.  97.
  60.  61. 242. 121. 128. 104. 265. 132. 283. 174. 129. 257. 137.  63.
  93. 232. 208. 261. 179. 258. 262.  51. 237.  71. 139. 268.  69. 317.
 249. 154. 192. 116.  81. 122. 259. 191. 292.  55. 107. 210.  91. 253.
  85. 252.  59.  78. 200.  78. 245. 175.  42. 127.  53.  94. 104. 199.
 265. 281. 248. 257. 215. 303. 170.  59. 277. 209. 138. 198. 124.  96.
 288. 225. 265. 101.  55. 198.  51. 252.  64. 220. 131. 212. 142. 103.
 155. 121.  86. 111.  65. 131.  51. 128. 141.  48. 109. 178.  88.  84.
 216. 150.  60.  96. 190.  74. 279. 182. 160. 245. 276. 174. 180. 150.
 196. 138.  97. 246. 321. 308. 109.  69. 182. 258. 161. 178. 214.  45.
 150. 160.  55. 197. 185. 268. 310. 123.  68.  72. 185. 144. 147. 168.
 178. 246. 151. 127.  83. 332. 152. 109.  90.  66. 214.  85. 129.  89.
 259. 229. 200.  77.  54.  31. 109. 206. 144. 118.  83. 242. 259.  72.
 163. 181. 141.  71. 137. 195. 179. 102. 131.  47. 235.  77. 198.  93.
 162. 225. 275. 183. 306.  81.  55. 146. 196. 230. 310.  40. 135. 346.
  43. 128.  77. 235.  49.  74.  92.  84. 263. 144. 142. 341. 115. 158.
 273.  85.  88. 220.  39.  80. 172. 217. 336.  52. 272. 115. 110. 131.
  71. 275. 118.  25. 100. 281. 221. 248. 200. 132.  91.  67. 202.  73.
  85. 275. 243.  66. 293. 236. 243.  87.  39. 217.  92. 296. 292. 142.
  50.  53. 104.  75. 120. 142. 143.  99.  65. 116. 233. 164.  95.  59.
 139. 145. 177. 185.  97.  42. 201. 241.  70.  78.  49. 103.  44. 111.
 191.  47. 182.  58. 155. 151.  79. 104. 143. 152. 170.  75. 200. 124.
  91.  49. 163.  53. 283. 178. 219. 200. 113. 113.  63. 114. 126. 274.
  88. 311.  83.  71. 134. 244.  65. 173.  57.  68. 141. 270. 134. 202.
 148.  64. 302.]

In [28]:
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.fit_transform(X_test)

In [30]:
ridge=Ridge(alpha=1.0)
ridge.fit(X_train_scaled,y_train)

Ridge()

In [31]:
y_pred=ridge.predict(X_test_scaled)

In [37]:
y_pred

array([150.46931275, 191.64159534, 147.10489616, 308.43542813,
       135.02302626, 102.29074171, 269.03974083, 195.92345439,
       100.92414686, 119.73816416, 104.80555202, 180.16661082,
        66.86874969, 221.93428349, 112.66327951, 143.21640243,
       232.99799347, 264.13391316, 211.74409191, 231.83055474,
       219.39522728,  97.66817103,  81.02919446, 202.81752572,
       165.72269102, 173.44819983, 201.81436578, 194.85630464,
        58.31564118, 120.94825204, 184.5916935 ,  98.47646192,
       142.19093892, 197.91110611, 182.85780498, 203.60243519,
       135.97722216, 131.22755645, 160.56351303,  68.400685  ,
        83.75962835, 120.9262837 , 178.54120658, 165.89357286,
       186.89853404,  71.70290358,  82.79735027, 124.83317838,
        64.19121363, 177.46748941, 162.91379381,  73.42394533,
       115.56556633, 120.13017034, 189.63586098, 166.02013162,
       105.04192014, 222.82467537, 129.96770893,  84.59228266,
       198.76489298, 217.2828618 , 151.4164998 , 119.56660218,
       141.61182431, 216.38753736, 184.92187667, 178.7483058 ,
       133.77720276, 155.5554202 , 196.25146583, 212.47761534,
       251.97569271, 157.61728472,  90.51035872, 169.62691394,
       206.25387108, 220.66075746, 171.22793709, 217.54237341,
       120.17651778, 151.06906532,  62.7905179 ,  65.81274886,
       126.57508805,  90.08785156,  91.75780709,  65.82590622,
       176.3852666 ])

In [38]:
y_test

array([219.,  70., 202., 230., 111.,  84., 242., 272.,  94.,  96.,  94.,
       252.,  99., 297., 135.,  67., 295., 264., 170., 275., 310.,  64.,
       128., 232., 129., 118., 263.,  77.,  48., 107., 140., 113.,  90.,
       164., 180., 233.,  42.,  84., 172.,  63.,  48., 108., 156., 168.,
        90.,  52., 200.,  87.,  90., 258., 136., 158.,  69.,  72., 171.,
        95.,  72., 151., 168.,  60., 122.,  52., 187., 102., 214., 248.,
       181., 110., 140., 202., 101., 222., 281.,  61.,  89.,  91., 186.,
       220., 237., 233.,  68., 190.,  96.,  72., 153.,  98.,  37.,  63.,
       184.])

In [40]:
print("MSE: ",mean_squared_error(y_pred,y_test))
print("R squared error: ",r2_score(y_pred,y_test))

MSE:  2956.269582333193
R squared error:  0.025786467840890448

In [42]:
lasso=Lasso(alpha=1.0)

In [43]:
lasso.fit(X_train_scaled,y_train)

Lasso()

In [44]:
y_pred_lasso=lasso.predict(X_test_scaled)

In [45]:
print("MSE:", mean_squared_error(y_test, y_pred_lasso))
print("R²:", r2_score(y_test, y_pred_lasso))

MSE: 2873.478940805048
R²: 0.457645028455522

In [48]:
print(ridge.coef_)

[  1.80734179 -11.44818951  25.73269892  16.73429974 -34.67195409
  17.05307485   3.36991411  11.76426044  31.3783838    2.45813922]

In [49]:
print(lasso.coef_)

[ 0.68703212 -9.29751904 26.21922482 15.65731357 -8.2281718  -0.
 -9.02408714  3.42086059 22.63646533  2.09864712]

Lets see which feature is eliminated using lasso

In [50]:
for feature, coef in zip(X.columns, lasso.coef_):
    print(feature, ":", coef)

age : 0.6870321189342089
sex : -9.297519041249917
bmi : 26.219224821372148
bp : 15.657313572919806
s1 : -8.228171802431133
s2 : -0.0
s3 : -9.024087140076444
s4 : 3.420860590218421
s5 : 22.636465325281904
s6 : 2.0986471248744203